export const CREATE_TOURNAMENT_REQUEST = 'CREATE_TOURNAMENT_REQUEST';
export const CREATE_TOURNAMENT_SUCCESS = 'CREATE_TOURNAMENT_SUCCESS';
export const CREATE_TOURNAMENT_FAIL = 'CREATE_TOURNAMENT_FAIL';

export const GET_TOURNAMENTS_REQUEST = 'GET_TOURNAMENTS_REQUEST';
export const GET_TOURNAMENTS_SUCCESS = 'GET_TOURNAMENTS_SUCCESS';
export const GET_TOURNAMENTS_FAIL = 'GET_TOURNAMENTS_FAIL';

export const UPDATE_TOURNAMENT_ROUND_STATUS_REQUEST = 'UPDATE_TOURNAMENT_ROUND_STATUS_REQUEST';
export const UPDATE_TOURNAMENT_ROUND_STATUS_SUCCESS = 'UPDATE_TOURNAMENT_ROUND_STATUS_SUCCESS';
export const UPDATE_TOURNAMENT_ROUND_STATUS_FAIL = 'UPDATE_TOURNAMENT_ROUND_STATUS_FAIL';

export const CLEAN_TOURNAMENT_DETAIL = 'CLEAN_TOURNAMENT';