export const CREATE_MATCH_SCORE_EVENT_REQUEST = 'CREATE_MATCH_SCORE_EVENT_REQUEST';
export const CREATE_MATCH_SCORE_EVENT_SUCCESS = 'CREATE_MATCH_SCORE_EVENT_SUCCESS';
export const CREATE_MATCH_SCORE_EVENT_FAIL = 'CREATE_MATCH_SCORE_EVENT_FAIL';

export const GET_ALL_MATCH_SCORE_EVENTS_REQUEST = 'GET_ALL_MATCH_SCORE_EVENTS_REQUEST';
export const GET_ALL_MATCH_SCORE_EVENTS_SUCCESS = 'GET_ALL_MATCH_SCORE_EVENTS_SUCCESS';
export const GET_ALL_MATCH_SCORE_EVENTS_FAIL = 'GET_ALL_MATCH_SCORE_EVENTS_FAIL';

export const LOCK_SCORE_COUNTER_REQUEST = 'LOCK_SCORE_COUNTER_REQUEST';
export const LOCK_SCORE_COUNTER_SUCCESS = 'LOCK_SCORE_COUNTER_SUCCESS';
export const LOCK_SCORE_COUNTER_FAIL = 'LOCK_SCORE_COUNTER_FAIL';

export const UNLOCK_SCORE_COUNTER_REQUEST = 'UNLOCK_SCORE_COUNTER_REQUEST';
export const UNLOCK_SCORE_COUNTER_SUCCESS = 'UNLOCK_SCORE_COUNTER_SUCCESS';
export const UNLOCK_SCORE_COUNTER_FAIL = 'UNLOCK_SCORE_COUNTER_FAIL';

export const VERIFY_SCORE_COUNTER_REQUEST = 'VERIFY_SCORE_COUNTER_REQUEST';
export const VERIFY_SCORE_COUNTER_SUCCESS = 'VERIFY_SCORE_COUNTER_SUCCESS';
export const VERIFY_SCORE_COUNTER_FAIL = 'VERIFY_SCORE_COUNTER_FAIL';