export const GET_TOURNAMENT_DETAIL_REQUEST = 'GET_TOURNAMENT_DETAIL_REQUEST';
export const GET_TOURNAMENT_DETAIL_SUCCESS = 'GET_TOURNAMENT_DETAIL_SUCCESS';
export const GET_TOURNAMENT_DETAIL_FAIL = 'GET_TOURNAMENT_DETAIL_FAIL';

export const ROUND_ROBIN_REQUEST = 'ROUND_ROBIN_REQUEST';
export const ROUND_ROBIN_SUCCESS = 'ROUND_ROBIN_SUCCESS';
export const ROUND_ROBIN_FAIL = 'ROUND_ROBIN_FAIL';

export const OTHER_TYPE_REQUEST = 'OTHER_TYPE_REQUEST';
export const OTHER_TYPE_SUCCESS = 'OTHER_TYPE_SUCCESS';
export const OTHER_TYPE_FAIL = 'OTHER_TYPE_FAIL';

export const ROUND_ROBIN_RANKINGS_REQUEST = 'ROUND_ROBIN_RANKINGS_REQUEST';
export const ROUND_ROBIN_RANKINGS_SUCCESS = 'ROUND_ROBIN_RANKINGS_SUCCESS';
export const ROUND_ROBIN_RANKINGS_FAIL = 'ROUND_ROBIN_RANKINGS_FAIL';

export const GET_MATCHES_REQUEST = 'GET_MATCHES_REQUEST';
export const GET_MATCHES_SUCCESS = 'GET_MATCHES_SUCCESS';
export const GET_MATCHES_FAIL = 'GET_MATCHES_FAIL';

export const UPDATE_MATCH_REQUEST = 'UPDATE_MATCH_REQUEST';
export const UPDATE_MATCH_SUCCESS = 'UPDATE_MATCH_SUCCESS';
export const UPDATE_MATCH_FAIL = 'UPDATE_MATCH_FAIL';



