export const CREATE_PLAYER_REQUEST = 'CREATE_PLAYER_REQUEST';
export const CREATE_PLAYER_SUCCESS = 'CREATE_PLAYER_SUCCESS';
export const CREATE_PLAYER_FAIL = 'CREATE_PLAYER_FAIL';

export const GET_PLAYERS_REQUEST = 'GET_PLAYERS_REQUEST';
export const GET_PLAYERS_SUCCESS = 'GET_PLAYERS_SUCCESS';
export const GET_PLAYERS_FAIL = 'GET_PLAYERS_FAIL';

export const CLEAN_PLAYERS = 'CLEAN_PLAYERS';