export const CREATE_MATCH_REQUEST = 'CREATE_MATCH_REQUEST';
export const CREATE_MATCH_SUCCESS = 'CREATE_MATCH_SUCCESS';
export const CREATE_MATCH_FAIL = 'CREATE_MATCH_FAIL';

export const GET_MATCHES_REQUEST = 'GET_MATCHES_REQUEST';
export const GET_MATCHES_SUCCESS = 'GET_MATCHES_SUCCESS';
export const GET_MATCHES_FAIL = 'GET_MATCHES_FAIL';